const CATEGORIES = {
  jobs: [
    "accounting+finance",
    "admin/office",
    "arch/engineering",
    "art/media/design",
    "biotech/science",
    "business/mgmt",
    "customer service",
    "education",
    "etc/misc",
    "food/bev/hosp",
    "general labor",
    "government",
    "human resources",
    "legal/paralegal",
    "manufacturing",
    "marketing/pr/ad",
    "medical/health",
    "nonprofit sector",
    "real estate",
    "retail/wholesale",
    "sales/biz dev",
    "salon/spa/fitness",
    "security",
    "skilled trade/craft",
    "software/qa/dba",
    "systems/network",
    "technical support",
    "transport",
    "tv/film/video",
    "web/info design",
    "writing/editing",
  ],
  sale: [
    "antiques",
    "appliances",
    "arts+crafts",
    "atv/utv/sno",
    "auto parts",
    "aviation",
    "baby+kid",
    "barter",
    "beauty+hlth",
    "bike parts",
    "bikes",
    "boat parts",
    "boats",
    "books",
    "business",
    "cars+trucks",
    "cds/dvd/vhs",
    "cell phones",
    "clothes+acc",
    "collectibles",
    "computer parts",
    "computers",
    "electronics",
    "farm+garden",
    "free",
    "furniture",
    "garage sale",
    "general",
    "heavy equip",
    "household",
    "jewelry",
    "materials",
    "motorcycle parts",
    "motorcycles",
    "music instr",
    "photo+video",
    "rvs+camp",
    "sporting",
    "tickets",
    "tools",
    "toys+games",
    "trailers",
    "video gaming",
    "wanted",
    "wheels+tires",
  ],
  housing: [
    "apts/housing",
    "housing swap",
    "housing wanted",
    "office/commercial",
    "parking/storage",
    "real estate for sale",
    "rooms/shared",
    "rooms wanted",
    "sublets/temporary",
    "vacation rentals",
  ],
  discussion: [
    "apple",
    "arts",
    "atheist",
    "autos",
    "beauty",
    "bikes",
    "celebs",
    "comp",
    "cosmos",
    "diet",
    "divorce",
    "dying",
    "eco",
    "feedbk",
    "film",
    "fixit",
    "food",
    "frugal",
    "gaming",
    "garden",
    "haiku",
    "help",
    "history",
    "housing",
    "jobs",
    "jokes",
    "legal",
    "manners",
    "marriage",
    "money",
    "music",
    "open",
    "parent",
    "pets",
    "philos",
    "photo",
    "politics",
    "psych",
    "recover",
    "religion",
    "rofo",
    "science",
    "spirit",
    "sports",
    "super",
    "tax",
    "travel",
    "tv",
    "vegan",
    "words",
    "writing",
  ],
  services: [
    "automotive",
    "beauty",
    "cell/mobile",
    "computer",
    "creative",
    "cycle",
    "event",
    "farm+garden",
    "financial",
    "health/well",
    "household",
    "labor/move",
    "legal",
    "lessons",
    "marine",
    "pet",
    "real estate",
    "skilled trade",
    "sm biz ads",
    "travel/vac",
    "write/ed/tran",
  ],
  community: [
    "activities",
    "artists",
    "childcare",
    "classes",
    "events",
    "general",
    "groups",
    "local news",
    "lost+found",
    "missed connections",
    "musicians",
    "pets",
    "politics",
    "rants&raves",
    "rideshare",
    "volunteers",
  ],
  gigs: [
    "computer",
    "creative",
    "crew",
    "domestic",
    "event",
    "labour",
    "lanet",
    "hgfd",
  ],
  resume: [],
};

module.exports = CATEGORIES;
